---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
install.packages("readxl")
library("readxl")

```

```{r}
library(dplyr)
library(tidyverse)
library(readxl)
```



1998
```{r}
funding98<-read_excel("C:/Users/mbunge/Desktop/stats133project/1998.xls")
funding98<-funding98[-(1:7),]
col_names <- c("CO","LEA ID","DISTRICT","EXPENDITURES","CURRENT EXPENSE ADA","CURRENT EXPENSE PER ADA","LEA TYPE")
names(funding98)<-col_names
mean_1998<-mean(as.numeric(funding98$`CURRENT EXPENSE PER ADA`))
mean_1998
```

1999
```{r}
funding99<-read_excel("C:/Users/mbunge/Desktop/stats133project/1999.xls")
funding99<-funding99[-(1:7),]
names(funding99)<-col_names
mean_1999<-mean(as.numeric(funding99$`CURRENT EXPENSE PER ADA`))
mean_1999
```

2000
```{r}
funding00<-read_excel("C:/Users/mbunge/Desktop/stats133project/2000.xls")
funding00<-funding00[-(1:7),]
names(funding00)<-col_names
mean_2000<-mean(as.numeric(funding00$`CURRENT EXPENSE PER ADA`))
mean_2000
```

2001
```{r}
funding01<-read_excel("C:/Users/mbunge/Desktop/stats133project/2001.xls")
funding01<-funding01[-(1:7),]
names(funding01)<-col_names
mean_2001<-mean(as.numeric(funding01$`CURRENT EXPENSE PER ADA`))
mean_2001
```

2002
```{r}
funding02<-read_excel("C:/Users/mbunge/Desktop/stats133project/2002.xls")
funding02<-funding02[-(1:8),]
names(funding02)<-col_names
funding02
mean_2002<-mean(as.numeric(funding02$`CURRENT EXPENSE PER ADA`))
mean_2002
```

2003
```{r}
funding03<-read_excel("C:/Users/mbunge/Desktop/stats133project/2003.xls")
funding03<-funding03[-(1:7),]
names(funding03)<-col_names
mean_2003<-mean(as.numeric(funding03$`CURRENT EXPENSE PER ADA`))
mean_2003
```

2004
```{r}
funding04<-read_excel("C:/Users/mbunge/Desktop/stats133project/2004.xls")
funding04<-funding04[-(1:7),]
names(funding04)<-col_names
mean_2004<-mean(as.numeric(funding04$`CURRENT EXPENSE PER ADA`))
mean_2004
```

2005
```{r}
file_2005<-read_excel("C:/Users/mbunge/Desktop/stats133project/2005.xls")
file_2005<-file_2005[-(1:7),]
new_names <- c("CO","LEA ID","DISTRICT","EXPENDITURES","CURRENT EXPENSE ADA","CURRENT EXPENSE PER ADA","LEA TYPE")
names(file_2005)<-new_names
mean_2005<-mean(as.numeric(file_2005$`CURRENT EXPENSE PER ADA`))
mean_2005
```


2006
```{r}
file_2006<-read_excel("C:/Users/mbunge/Desktop/stats133project/2006.xls")
file_2006<-file_2006[-(1:8),]
names(file_2006)<-new_names
mean_2006<-mean(as.numeric(file_2006$`CURRENT EXPENSE PER ADA`))
mean_2006
```

2007
```{r}
file_2007<-read_excel("C:/Users/mbunge/Desktop/stats133project/2007.xls")
file_2007<-file_2007[-(1:8),]
names(file_2007)<-new_names
mean_2007<-mean(as.numeric(file_2007$`CURRENT EXPENSE PER ADA`))
mean_2007
```

2008
```{r}
file_2008<-read_excel("C:/Users/mbunge/Desktop/stats133project/2008.xls")
file_2008<-file_2008[-(1:8),]
names(file_2008)<-new_names
mean_2008<-mean(as.numeric(file_2008$`CURRENT EXPENSE PER ADA`))
mean_2008
```

2009
```{r}
file_2009<-read_excel("C:/Users/mbunge/Desktop/stats133project/2009.xls")
file_2009<-file_2009[-(1:7),]
names(file_2009)<-new_names
mean_2009<-mean(as.numeric(file_2009$`CURRENT EXPENSE PER ADA`))
mean_2009
```

2010
```{r}
file_2010<-read_excel("C:/Users/mbunge/Desktop/stats133project/2010.xls")
file_2010<-file_2010[-(1:7),]
names(file_2010)<-new_names
mean_2010<-mean(as.numeric(file_2010$`CURRENT EXPENSE PER ADA`))
mean_2010
```

2011
```{r}
file_2011<-read_excel("C:/Users/mbunge/Desktop/stats133project/2011.xls")
file_2011<-file_2011[-(1:7),]
names(file_2011)<-new_names
mean_2011<-mean(as.numeric(file_2011$`CURRENT EXPENSE PER ADA`))
mean_2011
```

2012
```{r}
file_2012<-read_excel("C:/Users/mbunge/Desktop/stats133project/2012.xls")
file_2012<-file_2012[-(1:7),]
names(file_2012)<-new_names
mean_2012<-mean(as.numeric(file_2012$`CURRENT EXPENSE PER ADA`))
mean_2012
```

2013
```{r}
file_2013<-read_excel("C:/Users/mbunge/Desktop/stats133project/2013.xls")
file_2013<-file_2013[-(1:7),]
names(file_2013)<-new_names
mean_2013<-mean(as.numeric(file_2013$`CURRENT EXPENSE PER ADA`))
mean_2013
```

Create Data Frame for 2006 to 2013
```{r}
year<-c(1998:2013)
avg_current_expense_per_ada<-c(mean_1998,mean_1999,mean_2000,mean_2001,mean_2002,mean_2003,mean_2004,mean_2005,mean_2006,mean_2007,mean_2008,mean_2009,mean_2010,mean_2011,mean_2012,mean_2013)
funding2006_2013<-data.frame(year,avg_current_expense_per_ada)
funding2006_2013

```
```